apiVersion: v1
kind: Namespace
metadata:
  name: redis-operator
  labels:
    app.kubernetes.io/managed-by: redis-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    app.kubernetes.io/managed-by: redis-operator
