apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: redis
  labels:
    app.kubernetes.io/name: redis-cluster
    app.kubernetes.io/managed-by: redis-operator
type: Opaque
stringData:
  # 默认密码，对应 default 用户的认证密码
  password: "123456"
